consul mysql health check and waiter.sh mysql condition

diff --git a/pmmdemo/provision_scripts/percona_group_replication_81.yml b/pmmdemo/provision_scripts/percona_group_replication_81.yml
--- a/pmmdemo/provision_scripts/percona_group_replication_81.yml
+++ b/pmmdemo/provision_scripts/percona_group_replication_81.yml
@@ -33,7 +33,7 @@ runcmd:
   - systemctl enable mysql
   - systemctl start mysql
   - bash /root/init-mysql.sh
-  - sleep 10 && bash /tmp/waiter.sh mysql
+  - bash /tmp/waiter.sh mysql
   - pmm-admin add mysql --metrics-mode=push --username=pmm-admin --password='${mysql_root_password}' --cluster='percona-group-replication-81' --replication-set='percona-group-replication-81' --environment='"${environment_name}" --query-source=slowlog --service-name=${name}
   - wget --quiet https://github.com/ncabatoff/process-exporter/releases/download/v0.7.10/process-exporter_0.7.10_linux_386.rpm
   - yum -y install process-exporter_0.7.10_linux_386.rpm
@@ -53,29 +53,33 @@ write_files:
       search ${local_domain} ec2.internal
       options timeout:2 attempts:5
       nameserver 10.0.0.2
-  - path: /root/consul-check-mysql.sh
-    permissions: "0700"
+  - path: /tmp/consul-check-mysql.sh
+    permissions: "0755"
     content: |
       #!/bin/bash
       # Set MySQL server credentials
       MYSQL_USER="consul-health-check"
       MYSQL_PASSWORD="${mysql_root_password}"
       MYSQL_SOCKET="/data/mysql.sock"
+      while true ; do
+        # Attempt to connect using MySQL Shell with a 2-second timeout
+        mysql --socket="$MYSQL_SOCKET" --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" --connect-timeout=2 << EOF
 
-      # Attempt to connect using MySQL Shell with a 2-second timeout
-      mysqlsh --socket="$MYSQL_SOCKET" --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" --connect-timeout=2 << EOF
+        SELECT 1;
 
-      SELECT 1;
+        EOF
 
-      EOF
+        # Check the exit status of mysqlsh to determine connection success
+        if [[ $? -eq 0 ]]; then
+          echo "Successfully connected to MySQL service."
+          exit 0
+        else
+          echo -n "Connection attempt to MySQL service failed. Sleeping 1 second... "
+          date
+          sleep 1
+        fi
 
-      # Check the exit status of mysqlsh to determine connection success
-      if [[ $? -ne 0 ]]; then
-        echo "Error: Failed to connect to MySQL server." >&2
-        exit 1
-      fi
-
-      echo "Connection to MySQL server successful."
+      done
   - path: /etc/consul.d/consul.hcl
     permissions: "0644"
     content: |
@@ -109,6 +113,16 @@ write_files:
             "Success_before_passing": 3,
             "Timeout": "2s",
             "args": ["mysqladmin", "ping", "--host=127.0.0.1", "--port=3306", "--user='consul-health-check'", "--password=${mysql_root_password}"]
+            },
+            {
+            "ID": "percona-group-replication_check_script",
+            "Interval": "3s",
+            "Name": "Check for MySQL running on ${name}.",
+            "Notes": "Check for MySQL running on ${name}. Monitoring of MySQL metrics are enabled with this service.",
+            "ServiceID": "percona-group-replication_check_script",
+            "Success_before_passing": 3,
+            "Timeout": "3s",
+            "args": [ "bash", "/tmp/consul-check-mysql.sh" ]
             }
           ]
         }
@@ -159,19 +173,19 @@ write_files:
           echo "process-exporter check is not passing. Will retry in 3 seconds..."
           sleep 3
         done
-      elif [[ $service == "proxysql" ]]; then
-        # proxysql
+      elif [[ $service == "mysql" ]]; then
+        # mysql
         while true; do
-          # Get the status of the Proxysql check
-          status=$(dig @127.0.0.1 -p 8600 proxysql.service.consul SRV | awk '/SRV.*proxysql.${environment_name}.local.$/ {print $1}')
+          # Get the status of the mysql_check_http check
+          status=$(dig @127.0.0.1 -p 8600 ${name}.mysql.service.consul SRV | awk '/SRV.*${fqdn}\.$/ {print $1}')
 
-          if [[ $status == "proxysql.service.consul." ]]; then
-            echo "ProxySQL check is passing."
+          if [[ $status == "${name}.mysql.service.consul." ]]; then
+            echo "mysql check is passing."
             exit 0
           fi
 
           # If the check is not passing, wait for a short interval and try again
-          echo "ProxySQL check is not passing. Will retry in 3 seconds..."
+          echo "mysql check is not passing. Will retry in 3 seconds..."
           sleep 3
         done
       elif [[ $service == "readyz" ]] ; then
