consistency

diff --git a/pmmdemo/provision_scripts/percona_xtradb_cluster_80.yml b/pmmdemo/provision_scripts/percona_xtradb_cluster_80.yml
--- a/pmmdemo/provision_scripts/percona_xtradb_cluster_80.yml
+++ b/pmmdemo/provision_scripts/percona_xtradb_cluster_80.yml
@@ -6,25 +6,34 @@ prefer_fqdn_over_hostname: true
 preserve_hostname: false
 repo_upgrade: all
 
+packages:
+  - bind-utils
+  - curl
+
 bootcmd:
   - while [[ ! -b $(readlink -f /dev/nvme1n1) ]]; do echo "waiting for the disk..."; sleep 5; done
   - mkfs.xfs -L data /dev/nvme1n1
   - mkdir -p /data
 
+mounts:
+  - ["/dev/nvme1n1", "/data", "xfs", "defaults,noatime", "0", "2"]
+
 runcmd:
   - dnf config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
   - dnf -y install consul
-  - systemctl enable consul
-  - systemctl start consul
+  - systemctl enable consul && systemctl start consul
   - dnf -y install https://repo.percona.com/yum/percona-release-latest.noarch.rpm
-  - percona-release enable-only pxc-80 release
-  - percona-release enable tools release
-  - dnf -y install percona-xtradb-cluster
-  - percona-release enable tools pmm2-client
+  - percona-release setup -y ps-80
+  - PERCONA_TELEMETRY_DISABLE=1 dnf -y install percona-xtradb-cluster
   - percona-release setup -y pmm3-client
   - dnf -y install pmm-client
-  - systemctl enable mysql
-  - systemctl start mysql
+  - echo '!includedir /etc/my.cnf.d/' >> /etc/my.cnf
+  - chown mysql:mysql /data/
+  - semanage fcontext -a -t mysqld_db_t "/data(/.*)?" && restorecon -Rv /data
+  - for port in 4444 4567 4568; do semanage port -a -t mysqld_port_t -p tcp $port; done
+  - systemctl enable mysqld.service
+  - systemctl start mysqld.service
+  - systemctl status mysqld.service
   - bash /root/init-mysql.sh
   - bash /usr/local/bin/waiter.sh readyz
   - pmm-admin config --az="us-east-1f" --region="us-east-1" --metrics-mode=push --force --server-insecure-tls --server-url='https://admin:${pmm_password}@${pmm_server_endpoint}' ${fqdn} generic ${name}
@@ -33,9 +42,6 @@ runcmd:
   - dnf -y install https://github.com/ncabatoff/process-exporter/releases/download/v0.8.5/process-exporter_0.8.5_linux_amd64.rpm
   - bash /usr/local/bin/waiter.sh process-exporter
   - pmm-admin add external --group=processes --listen-port=9256 --environment="prod" --service-name="${name}-processes" --cluster="processes-cluster"
-
-mounts:
-  - ["/dev/nvme1n1", "/data", "xfs", "defaults,noatime", "0", "2"]
 
 write_files:
   - path: /etc/resolv.conf
@@ -55,12 +61,7 @@ write_files:
       MYSQL_SOCKET="/var/lib/mysql/mysql.sock"
       while true ; do
         # Attempt to connect using MySQL Shell with a 2-second timeout
-        mysql --socket="$MYSQL_SOCKET" --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" --connect-timeout=2 << EOF
-
-        SELECT 1;
-
-      EOF
-
+        mysql --socket="$MYSQL_SOCKET" --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" --connect-timeout=2 -e "SELECT 1"
         # Check the exit status of mysqlsh to determine connection success
         if [[ $? -eq 0 ]]; then
           echo "Successfully connected to MySQL service."
@@ -70,7 +71,6 @@ write_files:
           date
           sleep 1
         fi
-
       done
   - path: /etc/consul.d/consul.hcl
     permissions: "0644"
@@ -195,14 +195,13 @@ write_files:
         done
       fi
   - path: /root/.my.cnf
-    permissions: "0644"
+    permissions: "0600"
     content: |
       [client]
       user=root
       password="${mysql_root_password}"
 
   - path: /etc/my.cnf
-    permissions: "0644"
     content: |
       [mysqld]
 
@@ -212,7 +211,6 @@ write_files:
       report_port = 3306
       server_id   = ${index}
 
-
       # Generic
       #
       datadir=/data
@@ -221,28 +219,32 @@ write_files:
       pid-file=/var/run/mysqld/mysqld.pid
       log_error_verbosity=3
       log_error_suppression_list='MY-013360'
-      #proxy_protocol_networks=10.0.0.0/16
-      loose-validate_password.policy = 0
+      loose-validate_password.policy=0
+      percona_telemetry_disable=1
 
-
-      # Config binary and slow_query logs
+      # Configure binary logs
       #
-      log-bin=percona-xtradb-cluster-{index}-bin
+      log-bin
       binlog_format=ROW
       binlog_expire_logs_seconds=86400
       binlog_space_limit=10G
 
+      # Configure slow logs
+      #
       slow_query_log=ON
       slow_query_log_always_write_time=1
       slow_query_log_use_global_control=all
-      log_slow_rate_limit=1
+      log_slow_rate_limit=2       # Log every other slow query
       log_slow_rate_type='query'
       log_slow_admin_statements=ON
       log_slow_replica_statements=ON
       log_slow_verbosity=full
       long_query_time=0
-      #max_slowlog_size=3G
-      #max_slowlog_files=3
+
+      # InnoDB
+      #
+      innodb_buffer_pool_size=1G
+      innodb_flush_method=O_DIRECT
 
       # Configure statistics
       #
@@ -252,35 +254,15 @@ write_files:
 
       # wsrep
       #
-
-      # Cluster name
       wsrep_cluster_name=pxc-80-cluster
-
-      # If wsrep_node_name is not specified,  then system hostname will be used
       wsrep_node_name=${name}
-
-      # Cluster connection URL contains IPs of nodes. If no IP is found, this implies that a new cluster needs to be created, in order to do that you need to bootstrap this node
       wsrep_cluster_address=gcomm://percona-xtradb-cluster-0,percona-xtradb-cluster-1,percona-xtradb-cluster-2
-
-      # Path to Galera library
       wsrep_provider=/usr/lib64/galera4/libgalera_smm.so
-
-      # Slave thread to use
       wsrep_applier_threads=8
-
-      # Enable logging of conflicting statements
       wsrep_log_conflicts
-
-      # This changes how InnoDB autoincrement locks are managed and is a requirement for Galera
       innodb_autoinc_lock_mode=2
-
-      # pxc_strict_mode allowed values: DISABLED,PERMISSIVE,ENFORCING,MASTER
       pxc_strict_mode=ENFORCING
-
-      # disable encryption of cluster traffic
       pxc_encrypt_cluster_traffic=OFF
-
-      # SST method
       wsrep_sst_method=xtrabackup-v2
 
       [sst]
@@ -289,24 +271,22 @@ write_files:
       !includedir /etc/my.cnf.d/
 
   - path: /root/init-mysql.sh
-    permissions: "0500"
     content: |
       #!/bin/bash
 
       # This need not be run on the replicas because replication will propagate them everywhere
       provision_users() {
-        INITIAL_ROOT_PASSWORD=$(grep "root@localhost:" /var/log/mysqld.log | tail -n1 | awk '{print $NF}')
-
+        INITIAL_ROOT_PASSWORD=$(grep "root@localhost:" /var/log/mysqld.log | tail -n1 | rev | cut -d' ' -f1 | rev)
         if [ -n "$INITIAL_ROOT_PASSWORD" ]; then
-          mysql --connect-expired-password -uroot -p$INITIAL_ROOT_PASSWORD -Bse "ALTER USER root@'localhost' IDENTIFIED BY '${mysql_root_password}'; FLUSH PRIVILEGES;"
+          mysql --connect-expired-password -uroot -p$INITIAL_ROOT_PASSWORD -Bse "ALTER USER root@localhost IDENTIFIED BY '${mysql_root_password}'; FLUSH PRIVILEGES;"
+          if [ $? -ne 0 ]; then
+            echo "Error: Failed to change root password"
+          fi
           echo "Password for root@localhost successfully changed"
-          break
         else
-          echo "Error: Initial root password not found in /var/log/mysqld.log"
-          exit 1
-        fi      
-
-        mysql --defaults-file=/root/.my.cnf -Bse "CREATE USER 'pmm-admin'@'localhost' IDENTIFIED WITH mysql_native_password BY '${mysql_root_password}'; FLUSH PRIVILEGES;";
+          echo "Error: Initial root password not found in /data/mysqld.log"
+        fi
+        mysql --defaults-file=/root/.my.cnf -Bse "CREATE USER 'pmm-admin'@'localhost' IDENTIFIED BY '${mysql_root_password}'; FLUSH PRIVILEGES;";
         mysql --defaults-file=/root/.my.cnf -Bse "GRANT SELECT, PROCESS, REPLICATION CLIENT, RELOAD, BACKUP_ADMIN ON *.* TO 'pmm-admin'@'localhost'; FLUSH PRIVILEGES;";
         mysql --defaults-file=/root/.my.cnf -Bse "CREATE USER 'consul-health-check'@'localhost' IDENTIFIED BY '${mysql_root_password}' WITH MAX_USER_CONNECTIONS 2; FLUSH PRIVILEGES;";
         mysql --defaults-file=/root/.my.cnf -Bse "GRANT USAGE ON *.* TO 'consul-health-check'@'localhost'; FLUSH PRIVILEGES;";
@@ -315,23 +295,20 @@ write_files:
         mysql --defaults-file=/root/.my.cnf -Bse "CREATE DATABASE IF NOT EXISTS sbtest_proxysql;"
         mysql --defaults-file=/root/.my.cnf -Bse "CREATE DATABASE IF NOT EXISTS sbtest_haproxy;"
         mysql --defaults-file=/root/.my.cnf -Bse "GRANT ALL PRIVILEGES ON sbtest.* TO 'pmm-admin'@'localhost'; FLUSH PRIVILEGES;";
-        mysql --defaults-file=/root/.my.cnf -Bse "CREATE USER 'sysbench-direct-pxc'@'%' IDENTIFIED WITH mysql_native_password BY '${mysql_sysbench_password}'; FLUSH PRIVILEGES;";
+        mysql --defaults-file=/root/.my.cnf -Bse "CREATE USER 'sysbench-direct-pxc'@'%' IDENTIFIED BY '${mysql_sysbench_password}'; FLUSH PRIVILEGES;";
         mysql --defaults-file=/root/.my.cnf -Bse "GRANT ALL PRIVILEGES ON sbtest_direct.* TO 'sysbench-direct-pxc'@'%'; FLUSH PRIVILEGES;";
-        mysql --defaults-file=/root/.my.cnf -Bse "CREATE USER 'sysbench-proxysql-pxc'@'%' IDENTIFIED WITH mysql_native_password BY '${mysql_sysbench_password}'; FLUSH PRIVILEGES;";
+        mysql --defaults-file=/root/.my.cnf -Bse "CREATE USER 'sysbench-proxysql-pxc'@'%' IDENTIFIED BY '${mysql_sysbench_password}'; FLUSH PRIVILEGES;";
         mysql --defaults-file=/root/.my.cnf -Bse "GRANT ALL PRIVILEGES ON sbtest_proxysql.* TO 'sysbench-proxysql-pxc'@'%'; FLUSH PRIVILEGES;";
-        mysql --defaults-file=/root/.my.cnf -Bse "CREATE USER 'sysbench-haproxy-pxc'@'%' IDENTIFIED WITH mysql_native_password BY '${mysql_sysbench_password}'; FLUSH PRIVILEGES;";
+        mysql --defaults-file=/root/.my.cnf -Bse "CREATE USER 'sysbench-haproxy-pxc'@'%' IDENTIFIED BY '${mysql_sysbench_password}'; FLUSH PRIVILEGES;";
         mysql --defaults-file=/root/.my.cnf -Bse "GRANT ALL PRIVILEGES ON sbtest_haproxy.* TO 'sysbench-haproxy-pxc'@'%'; FLUSH PRIVILEGES;";
-        mysql --defaults-file=/root/.my.cnf -Bse "CREATE USER proxysql@'%' IDENTIFIED WITH mysql_native_password BY '${proxysql_monitor_password}'; FLUSH PRIVILEGES;";
+        mysql --defaults-file=/root/.my.cnf -Bse "CREATE USER proxysql@'%' IDENTIFIED BY '${proxysql_monitor_password}'; FLUSH PRIVILEGES;";
         mysql --defaults-file=/root/.my.cnf -Bse "GRANT ALL PRIVILEGES ON *.* TO proxysql@'%'; FLUSH PRIVILEGES;";
       }
-
 
       if [[ "${name}" == "percona-xtradb-cluster-0" ]]; then
           # If we are running on the primary node (i.e., index == 0), start the PXC instance in bootstrap mode.
           systemctl start mysql@bootstrap
-
           provision_users
-
           # Check 600 times (1200sec or 20min) if PXC is ready (all 3 nodes have joined and cluster is OPERATIONAL). Switch from bootstrapping to regular operation
           for (( i=1 ; i<=600 ; i++ )); do
               if $(mysql --defaults-file=/root/.my.cnf -h"${fqdn}" -Bse "show global status like 'wsrep_evs_state';" | grep "OPERATIONAL" >/dev/null) && \
